apiVersion: v1
data:
  mysql-backup.yml: |
    mysql_backup:
      debug: {{ .Values.mysql_backup.config.debug | quote }}
      stopOnFailure: {{ .Values.mysql_backup.config.stopOnFailure | quote }}
      {{- with .Values.mysql_backup.config.sources }}
      sources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql_backup.config.remotes }}
      remotes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mysql_backup.config.backups }}
      backups:
        {{- toYaml . | nindent 8 }}
      {{- end }}

kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "mysql_backup.fullname" . }}-config

